/**
 * Generated by tsnapi — public API snapshot of `bumped-version`
 */
// #region Types
export type GetBumpedVersionInput = {
  allowPrivate?: boolean;
  commitPath?: string;
  packageDir: string;
  git?: GitCommand;
  verbose?: (_: string) => void;
};
export type GitCommand = (_: string[]) => string;
// #endregion

// #region Functions
export declare function getBumpedVersion(_: GetBumpedVersionInput): string;
export declare function main(_?: string[]): string;
// #endregion