/**
 * Generated by tsnapi — public API snapshot of `bumped-version`
 */
// #region Functions
export declare function getBumpedVersion(_: string, _?: GitCommand, _?: GetBumpedVersionOptions): string;
export declare function main(_?: string[]): string;
// #endregion